blockchain:
    chains:
        ethereum:
            chain-id: 31337
            required-confirmations: 1
            rpc-url: http://127.0.0.1:8545
            staking-contract: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512"
            reward-contract: ${REWARD_CONTRACT_ADDRESS}
            api-private-key: ${API_PRIVATE_KEY}
security:
    aes:
        secret-key: ${AES_SECRET_KEY}
    jwt:
        expiration-time: 3600000
        secret-key: ${HASH_SEC_KEY}
server:
    port: 8080
spring:
    application:
        name: protocol-api
    config:
        import: env.properties
    data:
        redis:
            host: localhost
            port: 6379
    datasource:
        password: ${DATABASE_PASS}
        url: jdbc:postgresql://localhost:5432/blockwin?reWriteBatchedInserts=true
        username: postgres
    jpa:
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: create-drop
        open-in-view: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    batch_size: 50
                    batch_versioned_data: true
                order_inserts: true
                order_updates: true
    kafka:
        bootstrap-servers: localhost:9092
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            acks: all
            retries: 3
            properties:
                linger.ms: 5
                batch.size: 16384
        consumer:
            auto-offset-reset: latest
            enable-auto-commit: false
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            properties:
                spring.json.trusted.packages: "*"
        listener:
            ack-mode: manual

    sql:
        init:
            mode: always
